# $OpenBSD$

COMMENT=		"dynamic link library for Haskell"

V=			0.9.10
DISTNAME=		hs-plugins-${V}
CATEGORIES=		devel
MAINTAINER=		Don Stewart <dons@openbsd.org>
HOMEPAGE= 		http://www.cse.unsw.edu.au/~dons/hs-plugins/
MASTER_SITES=		${HOMEPAGE}

MODULES=		ghc
CONFIGURE_STYLE=	gnu dest

# LGPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
