---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Turbinado.SessionHandlers.GenericDB.SessionDBInfo.SessionData where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
sessionData :: Table
    ((RecCons SessionId (Expr Int)
      (RecCons DataKey (Expr String)
       (RecCons Value (Expr String)
        (RecCons DataExpires (Expr (Maybe UTCTime)) RecNil)))))

sessionData = baseTable "sessiondata" $
              hdbMakeEntry SessionId #
              hdbMakeEntry DataKey #
              hdbMakeEntry Value #
              hdbMakeEntry DataExpires

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- SessionId Field
---------------------------------------------------------------------------

data SessionId = SessionId

instance FieldTag SessionId where fieldName _ = "sessionid"

sessionId :: Attr SessionId Int
sessionId = mkAttr SessionId

---------------------------------------------------------------------------
-- Key Field
---------------------------------------------------------------------------

data DataKey = DataKey

instance FieldTag DataKey where fieldName _ = "datakey"

datakey :: Attr DataKey String
datakey = mkAttr DataKey

---------------------------------------------------------------------------
-- Value Field
---------------------------------------------------------------------------

data Value = Value

instance FieldTag Value where fieldName _ = "value"

value :: Attr Value String
value = mkAttr Value

---------------------------------------------------------------------------
-- DataExpires Field
---------------------------------------------------------------------------

data DataExpires = DataExpires

instance FieldTag DataExpires where fieldName _ = "dataexpires"

dataExpires :: Attr DataExpires (Maybe UTCTime)
dataExpires = mkAttr DataExpires
