---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Turbinado.SessionHandlers.GenericDB.SessionDBInfo where

import Database.HaskellDB.DBLayout

import qualified Turbinado.SessionHandlers.GenericDB.SessionDBInfo.Sessions
import qualified Turbinado.SessionHandlers.GenericDB.SessionDBInfo.SessionData

--import Turbinado.Utils (sessionDBname)

dbLayout :: String -> DBInfo
dbLayout sessionDBname = 
        DBInfo {dbname = sessionDBname,
        	 opts = DBOptions {useBString = False},
        	 tbls = [TInfo {tname = "Sessions",
        			cols = [CInfo {cname = "sessionId",
        				       descr = (IntT, False)},
        				CInfo {cname = "expires",
        				       descr = (UTCTimeT, True)}]},
        		 TInfo {tname = "SessionData",
        			cols = [CInfo {cname = "sessionId",
        				       descr = (IntT, False)},
        				CInfo {cname = "datakey",
        				       descr = (StringT, False)},
        				CInfo {cname = "value",
        				       descr = (StringT, False)},
        				CInfo {cname = "dataExpires",
        				       descr = (UTCTimeT, True)}]}]}
